src/SampleApp.Web/Models/Invoice/PayInvoiceModel.cs
namespace SampleApp.Web.Models.Invoice
{
    using System;

    using Microsoft.AspNetCore.Mvc.Rendering;

    using SampleApp.PresentationLayer.ApiModels;

    public class PayInvoiceModel
    {
        public Guid InvoiceId{ get; set; }
        public SelectList Invoices {  get; set; }
        public string SelectedInvoicesStr {  get; set; }
        public InvoiceDTO SelectedInvoices {  get; set; }
    }
}

src/SampleApp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SampleApp.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/SampleApp.Web/Controllers/InvoiceController.cs
using SampleApp.Core;
using SampleApp.Core.Entities;
using SampleApp.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace SampleApp.Web.Controllers
{
    using System.Collections.Generic;

    using AutoMapper;

    using Microsoft.AspNetCore.Mvc.Rendering;

    using SampleApp.Core.Interfaces.Services;
    using SampleApp.PresentationLayer.ApiModels;
    using SampleApp.Web.Models.Invoice;

    public class InvoiceController : Controller
    {
        private readonly IInvoiceService invoiceService;

        private readonly IMapper mapper;

        public InvoiceController(IInvoiceService invoiceService, IMapper mapper)
        {
            this.invoiceService = invoiceService;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var items = this.invoiceService.List();
            return View(this.mapper.Map<List<InvoiceDTO>>(items));
        }

        public IActionResult ChangeInvoice()
        {
            return Ok();
        }

        public IActionResult GetUnpaid()
        {
            var items = this.invoiceService.GetAllUnpaid();
            return View("Index", this.mapper.Map<List<InvoiceDTO>>(items));
        }

        public IActionResult PayInvoice()
        {
            var items = this.invoiceService.GetAllUnpaid();

            var vm = new PayInvoiceModel();
            vm.Invoices = new SelectList(this.mapper.Map<List<InvoiceDTO>>(items), "Id", "Id");
            return View(vm);
        }

        [HttpPost]
        public IActionResult PayInvoice(PayInvoiceModel payModel)
        {
            this.invoiceService.Pay(payModel.InvoiceId);
            return RedirectToAction("index", "home");
        }
    }
}

src/SampleApp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "AWS SAMPLE for MVC & WEB API Sample App";
}

<div class="row">
    <div class="col-md-6">
        <h2>Invoices (MVC)</h2>
        <ul>
            <li><a asp-area="" asp-controller="Invoice" asp-action="Index">Invoice List</a></li>
            <li><a asp-area="" asp-controller="Invoice" asp-action="GetUnpaid">Unpaid Invoice List</a></li>
            <li><a asp-area="" asp-controller="Invoice" asp-action="PayInvoice"> Pay Invoice</a></li>
            <li><a asp-area="" asp-controller="Invoices" asp-action="List"> Get Invoices no Auth</a></li>
            <li><a asp-area="" asp-controller="InvoicesAuth" asp-action="ListAuth"> Get invoices Auth</a></li>
            <li><a asp-area="" asp-controller="InvoicesAuth" asp-action="ListAuthWithToken"> Get invoices Auth with token</a></li>

        </ul>
    </div>
    <div class="col-md-6">
        <h2>Tools</h2>
        <ul>
            <li><a href="/swagger">API Documentation (Swagger)</a></li>
        </ul>
    </div>
</div>

src/SampleApp.Web/Views/Invoice/Index.cshtml
@{
    ViewData["Title"] = "ToDo List";
}
@model IEnumerable<SampleApp.PresentationLayer.ApiModels.InvoiceDTO>
<h2>To Do Items (MVC View)</h2>
@{
    var index = 0;
    foreach (var invoice in Model)
     {
         @await Html.PartialAsync("_InvoiceTemplate", invoice, new ViewDataDictionary(ViewData) { { "index", index } })
         index++;
     }
}

src/SampleApp.Web/Views/Invoice/PayInvoice.cshtml
@model SampleApp.Web.Models.Invoice.PayInvoiceModel

@{
    ViewData["Title"] = "PayInvoice";
}

<h2>Pay invoice</h2>

@using (Html.BeginForm("PayInvoice", "Invoice", FormMethod.Post))
{

    @Html.DropDownListFor(m => m.InvoiceId, Model.Invoices)
    <input type = "submit" value = "Send" />
}

src/SampleApp.Web/Views/Invoice/_InvoiceTemplate.cshtml
@model SampleApp.PresentationLayer.ApiModels.InvoiceDTO

<div>
    <h3>Invoice @Html.DisplayNameFor(model => model.Id) : @Html.DisplayFor(model => model.Id) </h3>
    <h4>@Html.DisplayNameFor(model => model.State): @Html.DisplayFor(model => model.State)</h4>
    <h5>@Html.DisplayNameFor(model => model.Items):</h5>

    <table class="table">
        <thead>
            <tr>
                <th style="width: 50%">
                    Title
                </th>
                <th style="width: 30%">
                    Quantity
                </th>
                <th style="width: 20%">
                    Price
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <hr />
</div>

src/SampleApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SampleApp.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SampleApp.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SampleApp.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

@await RenderSectionAsync("scripts", required: false).ConfigureAwait(false)
</body>
</html>